grids:
    # grid name, I just recommends to add the min resolution because it's common to not generate all the layers at the same resolution.
    swissgrid:
        # resolutions [required]
        resolutions: [1000, 500, 250, 100, 50, 20, 10, 5, 2]
        # bbox [required]
        bbox: [420000, 30000, 900000, 350000]
        # srs [required]
        srs: epsg:21781
        # unit [default to 'm']
        unit: m
        # [optional, default to 256]
        tile_size: 256
        # Used matrix identifier, 'resolution' or 'zoom' default to 'zoom'
        # 'resolution' don't work with MapCache
        matrix_identifier: zoom

# In all cache you can specify to generate the capabilities:
#
# 'http_url', he can include all attribute of this cache.
#
# 'http_urls' (array), he can include all attribute of this cache.
#
# 'http_url' and 'hosts' (array), 'http_url' can include all attribute of this cache,
# and host is a value from hosts.
caches:
    local:
        type: mbtiles
        folder: /media/sbrunner/Big/OSM/mbtiles
        # for GetCapabilities
        http_url:  http://localhost/osm/wsgi/tiles
    internet:
        type: mbtiles
        folder: php
        # for GetCapabilities
        http_url:  http://map.stephane-brunner.ch/mbtiles/wmts
        
# this defines some defaults values for all the layers
layer_default:
    # name of the grid to use (defined in grids)
    grid: swissgrid
    # file name extension
    extension: png
    # mime type used for the WMS request and the WMTS capabilities generation
    mime_type: image/png
    wmts_style: default
    # the WMTS dimensions definition [default to []]
    dimensions:
        -   name: DATE
            # the default value for the WMTS capabilities
            default: 2013
            # the generated value
            value: 2013
            # all the available values in the WMTS capabilities
            values: [2013]
    cost:
        # default to 40 [ms]
        tileonly_generation_time: 40
        # default to 30 [ms]
        tile_generation_time: 30
        # default to 30 [ms]
        metatile_generation_time: 30
        # default to 20 [ko]
        tile_size: 20

layers:
    mapnik:
        type: mapnik
        # buffer to gets the data
        # with mapnik it's better to use data_buffer than meta_buffer
        meta: on
        meta_buffer: 0
        data_buffer: 128
        mapfile: mapnik-stylesheets/generated.xml
        # the output_format used for the mapnik renderer, can be png, png256, jpeg, grid (grid_renderer)
        output_format: png

generation:
    default_cache: local
    default_layers: [mapnik]

    # maximum allowed consecutive errors, after it exit [default to 10]
    maxconsecutive_errors: 10

openlayers:
    # srs, center_x, center_y [required]
    srs: epsg:21781
    center_x: 600000
    center_y: 200000

cost:
    # [nb/month] [default to 10 000 000]
    request_per_layers: 10000000
    # GeoData size [Go] [default to 100]
    esb_size: 100
